### ISSUE TITLE
"'utf-8' codec can't decode byte 0xff in position 11: invalid start byte" popup; game doesn't launch

### ISSUE THREAD

**Issue by flourishknight** [kegsmr/sc4mp-client#10]
Hi,
When connected to the server, the server monitor appears and a pop with text "'utf-8' codec can't decode byte 0xff in position 11: invalid start byte" appears a couple of seconds later. This seems to stop the process of launching the game. 
![Capture](https://github.com/kegsmr/sc4mp-client/assets/85177614/87ad8890-044e-4f18-b78f-4b5e8abe12a4)
[sc4mpclient.log](https://github.com/kegsmr/sc4mp-client/files/12337891/sc4mpclient.log)

**Comment by kegsmr** [comment]
Thanks for the submission!

Basically the custom path set by the user seems to be causing an exception in the process_exists method called in the GameLauncher class. This method is used to determine whether the game has been closed or not.

For anyone else with the same error, you should try changing your custom path in the SC4 settings as a workaround.

**Comment by kegsmr** [comment]
Want to find a better solution to this

**Comment by kegsmr** [comment]
I think this is mostly fixed
