### ISSUE TITLE
Steam Error: `Application load error 5:0000065434`

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#13]
This error occurs on certain Steam installations of SimCity 4 when launching the game. Exact cause unknown.

Workarounds: 
- Place a copy of `Steam.exe` in the SimCity 4 installation directory.
- Reinstall SimCity 4 to the same drive where Steam is installed.
(credit: maoam)

![image](https://github.com/kegsmr/sc4mp-client/assets/86132624/f2fd522c-8525-4612-8d87-8183386ec42a)

**Comment by kegsmr** [comment]
Another workaround: reinstall SC4 to the same drive where Steam is installed.

**Comment by asier-ochoa** [comment]
This happens to me when I attempt to launch the steam version directly from the exe without the Steam executable. One option to fix this is for the game to be launched using [steam's browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) for steam users, especifically `steam://run/<id>//<args>/`.

**Comment by kegsmr** [comment]
> This happens to me when I attempt to launch the steam version directly from the exe without the Steam executable. One option to fix this is for the game to be launched using [steam's browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) for steam users, especifically `steam://run/<id>//<args>/`.

That's a great idea. I'll have to look into that.

**Comment by kegsmr** [comment]
Added support for Steam browser protocol in latest commit: https://github.com/kegsmr/sc4mp-client/commit/733de43dc879348946d99aa32b3f0af7300a1b1a

The only problem is that Steam gives you an annoying pop-up asking you to confirm that you want to launch the game with the specified arguments, before it launches the game. 

So by default, the Steam browser protocol will only be used when a custom game path is specified that points to a Steam installation of SC4. Since the launcher can't find Steam installations of SC4 on separate drives, this is typically when you'd need to specify a custom path. Conveniently this is also when the application load error occurs. The Steam installations of SC4 that do not have this error can be automatically found by the launcher, so in that case, the launcher will just launch the game directly.

We (hopefully) won't be seeing the application load error anymore.
