### ISSUE TITLE
utf-8' codec can't decode byte 0x85 in position 29: invalid start byte

### ISSUE THREAD

**Issue by ulisse99** [kegsmr/sc4mp-client#16]
When I exit the game session I get this error preventing the program from closing correctly causing the forced closure of the program through Task Manager. 

https://i.imgur.com/7nSvDPV.jpg

[sc4mpclient.log](https://github.com/kegsmr/sc4mp-client/files/12566927/sc4mpclient.log)

**Comment by kegsmr** [comment]
This should be fixed now
