### ISSUE TITLE
utf-8 codec error in loading sequence

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#19]
It's rather common and I have almost no clue why it happens.

[sc4mpclient.log](https://github.com/kegsmr/sc4mp-client/files/12582096/sc4mpclient.log)

Also: 
```[91m [10:32:31] [SC4MP/Thread-25] (ServerLoader) [ERROR] An error occurred while connecting to the server.

'utf-8' codec can't decode byte 0x9a in position 24: invalid start byte

Traceback (most recent call last):
  File "sc4mpclient.py", line 1926, in run
  File "sc4mpclient.py", line 2134, in load
  File "sc4mpclient.py", line 2234, in receive_or_cached
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 24: invalid start byte
```

Workaround: the problem seems to improve after clearing the cache

**Comment by iqionly** [comment]
I think this may appear when the plugins not support utf-8 codec. We better logging the plugin the server use, look the name or string may have

**Comment by kegsmr** [comment]
Think I figured it out. If someone wants to test it out, checkout the attached branch.
