### ISSUE TITLE
Launcher sometimes does not close after game closes

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#73]
According to HexHyte

**Comment by weewoo-meow** [comment]
Got the same problem. I bought the game from GOG.

**Comment by kegsmr** [comment]
Fixed in the next patch!

You'll be able to manually disconnect from the server if the `process_exists` method raises an exception, so long as the subprocess to launch the game has already exited.

Additionally, there will be an option to allow disconnect from the server whenever you'd like.

It will ask you first if you're sure you want to disconnect, just to be safe.
