### ISSUE TITLE
Crashes and gives no error message.

### ISSUE THREAD

**Issue by doodayev** [kegsmr/sc4mp-client#94]
Hi,
I originally had this client installed on my D: drive and the game was also on the D: drive but apparently this causes problems. I got an error message for it and someone was able to point out that installing the game itself to C: is probably a good idea. So I reinstalled the game to the C: drive and still it would crash but now I got no error message. The next thing that I thought of doing was reinstalling the client to the C: drive but I'd still crash with no error message. Also I'd like to point out that "uninstalling" still makes the shortcut point to the original install directory so if in the past it was "D:/Programs/SC4MP" and you tried installing to "C:/Documents/Sim City 4/SCMP4" or whatever (I am not being precise with these directories but those seem right), it'll still point to "D:/Programs/SC4MP". I tried tinkering some more by deleting all the files the server I was trying to connect to had downloaded and redownloading but still no dice.

Anyways here's the exception file and mini-dump which I discovered on accident. I'd appreciate it very much if you could make heads or tails of this! Had to put it in a zip file because Github is REALLY SILLY!!!
![image](https://github.com/user-attachments/assets/9f268eb3-5aba-4960-bdc4-ebbda4c0eb5e)

[ExceptionReportAndMiniDump.zip](https://github.com/user-attachments/files/16416818/ExceptionReportAndMiniDump.zip)

**Comment by kegsmr** [comment]
Hi, I think we managed to resolve this, right? It turned out to be a graphics driver issue?

**Comment by doodayev** [comment]
Yeah my RX 6600 was being really silly. AMD drivers are a mess. It turned out some other games also had issues. Call of Duty 2 had given me a gray screen when in-game but the menu and UI elements worked. Unreal Engine 4/5 games didn't work at all either. Other games seemed to work fine-ish. 

For this game in particular we solved it by just using software-rendering which gave pretty good performance even at 1080p on my Ryzen 5 3600. I think any CPU from Ryzen 1000 onwards and let's say Intel-8000 series onwards you could recommend someone to run on CPU graphics without blinking an eye if they have GPU driver issues.

**Comment by kegsmr** [comment]
Cool, I made a little guide on software rendering. Let me know if there's anything missing.

https://github.com/kegsmr/sc4mp-client/issues/103
